import type { GetServerSideProps, NextPage } from 'next'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Banner from '../components/banner'
import Header from '../components/header'
import UserFloatTarget from '../components/userFloatTarget'
import { IGitHubProfile } from '../types/users'

interface Props {
  user: IGitHubProfile
}

const Home: NextPage<Props> = ({ user }) => {
  return (
    <div className='min-h-screen bg-orange-50'>
      <Head>
        <title>🔥 DragOn | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header user={user} />
      <Banner />

      {user && <UserFloatTarget user={user} vertical="bottom" horizontal='right' />}

    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)

  return {
    props: {
      user: session?.user
    }
  }
}

export default Home
